# Que se debe tener en cuenta para que otros desarrolladores configuren su entorno local
spring.datasource.url=jdbc:mysql://localhost:3306/nameDatabase?createDatabaseIfNotExist=true
spring.datasource.username=
spring.datasource.password=